#!/bin/sh

FILENAME=""
TEMPLATE=""
TEMPLATE_DIR=""
GLOBAL_INSTALL_DIR=/usr/local/share/fileCreationTemplate/templates
USER_INSTALL_DIR=${HOME}/.local/share/fileCreationTemplate/templates
CURRENT_DIR=$(pwd)

if test -d $GLOBAL_INSTALL_DIR; then
  TEMPLATE_DIR=$GLOBAL_INSTALL_DIR
elif test -d $USER_INSTALL_DIR; then
  TEMPLATE_DIR=${USER_INSTALL_DIR}
else
  echo "\
  Can not find template folder.
  Program seems not correctly installed.
  Abort."
  exit 1
fi

printHelp() {
  echo "\
    ${0##*/} - Usage..."
}

listValidOptions() {
  echo "\
    All available (filetype) options:"
  for files in $(ls templates); do
    OPTION=$(echo $files | sed 's/\..*//' | sed 's/^/--/')
    echo "\
      $OPTION"
  done
}

while test $# -gt 0; do
  case $1 in
    --help)
      printHelp
      exit 0
      ;;
    --list-options|--list)
      listValidOptions
      exit 0
      ;;
    --*)
      TEMPLATE=$(ls ${TEMPLATE_DIR}/${1#--*}* 2> /dev/null)
      shift
      ;;
    -*)
      TEMPLATE=$(ls ${TEMPLATE_DIR}/${1#-*}* 2> /dev/null)
      shift
      ;;
    *)
      FILENAME=$1
      shift
      ;;
  esac
done

if test -n "${FILENAME}" -a -n "${TEMPLATE}"; then
  cp ${TEMPLATE} ${FILENAME}
else
  echo "No filename or template given"
  exit 1
fi
